# INFO: The below two commands should be ran, using the default causes lots of issues
# if you happen to have multiple windows spanning multiple monitors.
# For example, if you focus an Arc window on the main monitor, 
# then the focus on the secondary monitor will be moved to the Arc window 
# on the secondary monitor, which is not what you want.
# More info: https://nikitabobko.github.io/AeroSpace/guide.html
# Commands:
# defaults write com.apple.spaces spans-displays -bool true && killall SystemUIServer
# defaults write com.apple.dock expose-group-apps -bool true && killall Dock

# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []
after-startup-command = []

# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = true

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 5
inner.vertical =   5
outer.left =       10
outer.bottom =     10
# INFO: monitor.built-in is just for example, both have 5 right now.
outer.top =        [ { monitor."built-in" = 5 }, 5 ]
outer.right =      10

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'main'
6 = ['secondary', 'main']
7 = ['secondary', 'main']
8 = ['secondary', 'main']
9 = ['secondary', 'main']
A = ['secondary', 'main']
B = ['secondary', 'main']


[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, ctrl-cmd, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with ctrl-cmd + enter shortcut (like in i3)
# ctrl-cmd-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

# User Commands
cmd-alt-shift-ctrl-t = 'exec-and-forget open -a wezterm -n --args start'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
cmd-period = 'layout tiles horizontal vertical'
cmd-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
ctrl-cmd-h = 'focus left'
ctrl-cmd-j = 'focus down'
ctrl-cmd-k = 'focus up'
ctrl-cmd-l = 'focus right'
ctrl-cmd-c = 'focus-monitor --wrap-around next'
cmd-alt-shift-ctrl-l  = 'split vertical'
cmd-alt-shift-ctrl-j = 'split horizontal'

ctrl-cmd-g = 'workspace --wrap-around next'
ctrl-cmd-s = 'workspace --wrap-around prev'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
ctrl-cmd-shift-h = 'move left'
ctrl-cmd-shift-j = 'move down'
ctrl-cmd-shift-k = 'move up'
ctrl-cmd-shift-l = 'move right'
ctrl-cmd-shift-c = [ 'move-node-to-monitor --wrap-around next' ,  'focus-monitor --wrap-around next' ]

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
ctrl-cmd-shift-minus = 'resize smart -50'
ctrl-cmd-shift-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
ctrl-cmd-1 = 'workspace 1'
ctrl-cmd-2 = 'workspace 2'
ctrl-cmd-3 = 'workspace 3'
ctrl-cmd-4 = 'workspace 4'
ctrl-cmd-5 = 'workspace 5'
ctrl-cmd-6 = 'workspace 6'
ctrl-cmd-7 = 'workspace 7'
ctrl-cmd-8 = 'workspace 8'
ctrl-cmd-9 = 'workspace 9'
ctrl-cmd-p = 'workspace A'
ctrl-cmd-0 = 'workspace B'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
ctrl-cmd-shift-1 = [ 'move-node-to-workspace 2', 'workspace 1' ]
ctrl-cmd-shift-2 = [ 'move-node-to-workspace 2', 'workspace 2' ]
ctrl-cmd-shift-3 = [ 'move-node-to-workspace 3', 'workspace 3' ]
ctrl-cmd-shift-4 = [ 'move-node-to-workspace 4', 'workspace 4' ]
ctrl-cmd-shift-5 = [ 'move-node-to-workspace 5', 'workspace 5' ]
ctrl-cmd-shift-6 = [ 'move-node-to-workspace 6', 'workspace 6' ]
ctrl-cmd-shift-7 = [ 'move-node-to-workspace 7', 'workspace 7' ]
ctrl-cmd-shift-8 = [ 'move-node-to-workspace 8', 'workspace 8' ]
ctrl-cmd-shift-9 = [ 'move-node-to-workspace 9', 'workspace 9' ]
ctrl-cmd-shift-p = [ 'move-node-to-workspace A', 'workspace A' ]
ctrl-cmd-shift-0 = [ 'move-node-to-workspace B', 'workspace B' ]

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
ctrl-cmd-tab = 'workspace-back-and-forth'

# See: https://nikitabobko.github.io/AeroSpace/commands#mode
cmd-alt-shift-ctrl-c = 'mode service'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
c = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout

ctrl-cmd-shift-h = ['join-with left', 'mode main']
ctrl-cmd-shift-j = ['join-with down', 'mode main']
ctrl-cmd-shift-k = ['join-with up', 'mode main']
ctrl-cmd-shift-l = ['join-with right', 'mode main']
