#!/usr/bin/env sh

spacebar -m config position top
spacebar -m config height 32
spacebar -m config spacing_left 25
spacebar -m config padding_left 25
spacebar -m config spaces on
spacebar -m config title off
spacebar -m config spacing_right 20
spacebar -m config padding_right 25
spacebar -m config text_font "Fira Code:Bold:14.0"
spacebar -m config icon_font "Hack Nerd Font:Regular:20"
spacebar -m config background_color 0xff303046
spacebar -m config space_icon_color 0xff00ff00
spacebar -m config space_icon_color_secondary 0xff00ff00
spacebar -m config space_icon_color_tertiary 0xff00ff00
spacebar -m config foreground_color 0xffcdd6f4
spacebar -m config space_icon_color 0xffAAE9B4
spacebar -m config power_icon_color 0xffEBCB8B
spacebar -m config battery_icon_color 0xffcdd6f4
spacebar -m config dnd_icon_color 0xffE5E9F0
spacebar -m config clock_icon_color 0xffcdd6f4
spacebar -m config space_icon_strip   󰒱      󰶍 󰆼   
spacebar -m config power_icon_strip 󰂌 
spacebar -m config space_icon 
spacebar -m config clock_icon 
spacebar -m config dnd_icon 
spacebar -m config clock_format "%d/%m/%y %R"

echo "spacebar configuration loaded.."
