#!/usr/bin/env sh

spacebar -m config position           top
spacebar -m config height             26
spacebar -m config spacing_left       5
spacebar -m config spacing_right      5
spacebar -m config text_font          "Helvetica Neue:Bold:12.0"
spacebar -m config icon_font          "Font Awesome 5 Free:Solid:12"
spacebar -m config background_color   0xcc2E3440
spacebar -m config foreground_color   0xffD8DEE9
spacebar -m config space_icon_color   0xff81A1C1
spacebar -m config power_icon_color   0xffEBCB8B
spacebar -m config battery_icon_color 0xffA3BE8C
spacebar -m config dnd_icon_color     0xffE5E9F0
spacebar -m config clock_icon_color   0xffE5E9F0
spacebar -m config space_icon_strip                VIII IX X
spacebar -m config power_icon_strip    
spacebar -m config space_icon         
spacebar -m config clock_icon         
spacebar -m config dnd_icon           
spacebar -m config clock_format       "%d/%m/%y %R"

echo "spacebar configuration loaded.."

