return {
  'nvim-treesitter/nvim-treesitter',
  lazy = false,
  branch = 'master',
  build = ':TSUpdate',
  config = function()
    local configs = require('nvim-treesitter.configs')
    configs.setup({
      ensure_installed = {
        'bash',
        'c',
        'c_sharp',
        'css',
        'styled',
        'diff',
        'http',
        'html',
        'javascript',
        'java',
        'jsdoc',
        'json',
        'jsonc',
        'lua',
        'luadoc',
        'luap',
        'markdown',
        'markdown_inline',
        'printf',
        'python',
        'prisma',
        'query',
        'regex',
        'vue',
        'go',
        'toml',
        'tsx',
        'typescript',
        'terraform',
        'vim',
        'vimdoc',
        'xml',
        'yaml',
      },
      sync_install = false,
      highlight = { enable = true },
      indent = { enable = true },
    })
  end,
}
